{"name": "test_login_page[test_login_006-13488834010-000000-错误-输入的密码错误!-None]", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'find_element'", "trace": "self = <class 'my_app_test.Scripts.test_login.Test_Login'>\n\n    def setup_class(self):\n        # 实例化登陆对象\n        self.LP_obj = Login_Page(get_driver())\n        # 点击个人中心\n        sleep(5)\n>       self.LP_obj.click_sy_login_btn()\n\nScripts\\test_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPage\\login_page.py:10: in click_sy_login_btn\n    self.click_element(Page.sy_login_btn_XPATH)\nBase\\Base.py:40: in click_element\n    self.search_element(loc).click()\nBase\\Base.py:22: in search_element\n    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*loc))\nc:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nx = None\n\n>   return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*loc))\nE   AttributeError: 'NoneType' object has no attribute 'find_element'\n\nBase\\Base.py:22: AttributeError"}, "description": "\n        :param username: 用户名\n        :param passwd: 密码\n        :param get_mess: toast传参\n        :param expect_message: 预期toast消息\n        :param tag: 1 标记登陆成功用例\n        :return:\n        ", "parameters": [{"name": "case_num", "value": "'test_login_006'"}, {"name": "username", "value": "'13488834010'"}, {"name": "passwd", "value": "'000000'"}, {"name": "get_mess", "value": "'错误'"}, {"name": "expect_message", "value": "'输入的密码错误!'"}, {"name": "tag", "value": "None"}], "start": 1606967460806, "stop": 1606967460806, "uuid": "e760952c-1d64-4c07-96b9-e84cf8182e80", "historyId": "8928023a3c995c9dd839d6596784f46f", "testCaseId": "a4a0150438cc50307e30db7582a4b9c3", "fullName": "Scripts.test_login.Test_Login#test_login_page", "labels": [{"name": "parentSuite", "value": "Scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "SC-202010121356"}, {"name": "thread", "value": "25548-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Scripts.test_login"}]}